### ISSUE TITLE
Shared thumbnail file URI seems incorrect

### ISSUE THREAD

**Issue by kennylevinsen** [filcuc/thumbnailer#9]
The URI used for shared thumbnails is relative to file being thumbnailed. E.g., for a picture `/home/user/picture.png`, a relative URI to the picture would be like so: `picture.png`. However, thumbnailer uses `file://picture.png`.

The wording in the spec is rather confusing, but `picture.png` is what the in-progress glib work uses (https://gitlab.gnome.org/GNOME/glib/-/issues/654), and how the URI RFC defines relative URIs.

(I'll post a PR later.)

**Comment by filcuc** [comment]
@kennylevinsen 

> The filename of the thumbnail is also in the shared thumbnail repository the md5sum of the URI. But, because the URI is possibly not constant, only the filename part of the URI should be used, no directory parts.

I thought to still encode an URI but ok! thank you

**Comment by filcuc** [comment]
And what we should be put on the Thumb::URI png metadata? 
`picture.png`

**Comment by kennylevinsen** [comment]
> I thought to still encode an URI

Based on the confusing wording of the spec, I can also see it as interpreted that way. I'm planning to submit an MR to the spec to get that fixed while we're at it.

On that note, do you know of any *users* of shared thumbnails? Seems like a pretty neglected feature. :/

> And what we should be put on the Thumb::URI png metadata

The spec isn't clear on this. See https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/13, which suggests a change to the spec to specify it as also being 'picture.png'.

**Comment by filcuc** [comment]
@kennylevinsen IMHO shared thumbnails are great for network filesystem or folders shared with multiple users. My own use case is generating thumbnails for my picture folder in my NAS. I can use cron for pre-generate all the thumbnails and having ready for all the users (family members)
